name: glanzmann
favicon: null
layout_spectrum: 0.38031558273360133
typography_spectrum: 0.2055228070821613
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.641588190337643
  lightness: 0.8575897277332842
  saturation: 0.5191915344912559
  rhythmicContrast: 0.05670372280292213
purpose: []
